version: '3.5'

services:
  rmc:
    container_name: app-rmc
    build:
      context: .  
    volumes:
      - .:/app

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/app
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - rmc
    
  postgresql:
    image: postgres:latest
    container_name: postgresql-db
    restart: on-failure
    environment:
      POSTGRES_USER: rmc
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgresql-db
    ports:
      - "5432:5432"
    volumes:
      - .:/app

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq